spring:
    application:
        name: spring-cloud-config-demo
    config:
        import: optional:configserver:http://localhost:8888

management:
    endpoints:
        web:
            exposure:
                include: "*"
